name: pip_services3_data
version: 1.0.4
author: Sergey Seroukhov <seroukhov@gmail.com>
description: This package contains various design patterns for working with data and provides implementation of reusable data processing
homepage: https://github.com/pip-services3-dart/pip-services3-data-dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  pip_services3_commons: ">=1.0.2 <2.0.0"
  pip_services3_components: ">=1.0.2 <2.0.0"
  sprintf: "^4.0.0"

dev_dependencies:
  test: '>=1.14.2 <2.0.0'