name: pip_services3_data
version: 1.1.2
description: This package contains various design patterns for working with data and provides implementation of reusable data processing
homepage: https://github.com/pip-services3-dart/pip-services3-data-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.1.0
  pip_services3_commons: ^1.1.3
  pip_services3_components: ^1.1.1
  sprintf: ^6.0.0

dev_dependencies:
  test: ^1.17.12